# Generated by Django 5.1 on 2024-09-07 08:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Copun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True)),
                ('percent', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('expire_date', models.DateField()),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('order_id', models.IntegerField()),
                ('status', models.BooleanField()),
                ('price', models.FloatField()),
                ('copun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.copun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dargah', models.CharField(max_length=20)),
                ('trans_id', models.CharField(max_length=10)),
                ('status', models.BooleanField()),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factor', to='payment.factor')),
            ],
        ),
    ]
