# Generated by Django 5.1 on 2024-08-16 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Copun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('percent', models.IntegerField()),
                ('time', models.TimeField()),
                ('user', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('order', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dargah', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=30)),
                ('status', models.BooleanField()),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='first_fac', to='payment.factor')),
                ('factor2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='second_fac', to='payment.factor')),
            ],
        ),
    ]
