# Generated by Django 5.1 on 2024-08-16 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copun',
            old_name='time',
            new_name='date',
        ),
    ]
