# Generated by Django 5.1 on 2024-08-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_time_copun_date'),
    ]

    operations = [

    ]
