# Generated by Django 5.1 on 2024-09-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_factor_copun_alter_factor_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
