# Generated by Django 5.1 on 2024-09-09 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_factor_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
    ]
