# Generated by Django 5.1 on 2024-08-22 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_copun_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='factor2',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.factor'),
        ),
    ]
