# Generated by Django 5.1 on 2024-08-22 11:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_transaction_factor2_alter_transaction_factor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copun',
            name='date',
        ),
        migrations.AddField(
            model_name='copun',
            name='expire_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
