# Generated by Django 5.1 on 2024-09-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_transaction_trans_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
