# Generated by Django 5.1 on 2024-08-25 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_copun_date_copun_expire_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copun',
            old_name='title',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='factor',
            old_name='order',
            new_name='order_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='code',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.AddField(
            model_name='factor',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='copun',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='copun', to='payment.copun'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='trans_id',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factor', to='payment.factor'),
        ),
    ]
