# Generated by Django 5.1 on 2024-08-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_rename_title_copun_code_rename_order_factor_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.RemoveField(
            model_name='copun',
            name='user',
        ),
        migrations.AddField(
            model_name='copun',
            name='user',
            field=models.ManyToManyField(to='payment.user'),
        ),
    ]
