# Generated by Django 5.1 on 2024-08-25 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_user_email_remove_copun_user_copun_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Usr',
        ),
    ]
